rrbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  joints_position_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - joint1
      - joint2
    joint1:
      pid: {p: 100.0, i: 0.01, d: 10.0}
    joint2:
      pid: {p: 100.0, i: 0.01, d: 10.0}
